### ISSUE TITLE
doesn't build on ghc > 8.0RC3 

### ISSUE THREAD

**Issue by cartazio** [liyang/vector-th-unbox#16]
some TH changed in a breaking way at that point

@liyang would you like some help updating this?
cc @hvr @bergmark

**Comment by erikd** [comment]
Just hit this myself trying to install criterion.

**Comment by liyang** [comment]
Right, so it's http://git.haskell.org/ghc.git/commit/c3dafd9168827d0c32d7d9483aa223157f925026

I've pushed a fix, but will hold off releasing to Hackage until things settle down.

**Comment by hvr** [comment]
@liyang fyi, GHC 8.0.1 RC4 should be available from my ppa now, so if you restart the https://travis-ci.org/liyang/vector-th-unbox/jobs/124981422 job it should pass this time

**Comment by erikd** [comment]
Not sure what you would define as "settled down", but GHC 8.0.1 RC4 has been released :-).

**Comment by liyang** [comment]
@hvr Half the time Travis was still picking up RC3 for some reason. When RC4 ends up using the build cache from RC3 (should it be doing that?) it gave a bunch of errors:

```
cabal: Encountered missing dependencies:
data-default -any, vector >=0.7
```

I ended up deleting the build cache (quite a few times; while I was figuring out what was going on) to get everything to pass…

@erikd I didn't want to spend a few hours building RC4 myself. :)

Anyway, released to Hackage as [`vector-th-unbox-0.2.1.6`](http://hackage.haskell.org/package/vector-th-unbox-0.2.1.6).

**Comment by erikd** [comment]
And now I've got it. Thanks @liyang !

**Comment by hvr** [comment]
@liyang I'm afraid the build-cache is admittedly quite fragile when updating between RCs and I forgot to mention that the cache for the GHC 8.0 job needs to cleared... that's something that the v2 script (it's available already but I'm still tweaking it) based on cabal-1.24's new features handles in a robust way.
