### ISSUE TITLE
Can I have a fix for this warning? kthxbye

### ISSUE THREAD

**Issue by pacak** [liyang/vector-th-unbox#5]
Numeric/Polynomial.hs:532:27: Warning:
    Variable ‘r’ is implicitly quantified due to a context
    Use explicit forall syntax instead.
    This will become an error in GHC 7.12.
    In the type ‘(Unbox r) => Poly7 r -> (r, r, Poly5 r)’
    In a Template-Haskell quoted type

**Comment by liyang** [comment]
No code to fix here per se: the problem is between the monitor and the keyboard.
