### ISSUE TITLE
derivingUnbox accepts invalid constructor suffixes

### ISSUE THREAD

**Issue by liyang** [liyang/vector-th-unbox#7]
Despite the [documentation noting the fact](http://hackage.haskell.org/package/vector-th-unbox-0.2.1.0/docs/Data-Vector-Unboxed-Deriving.html#v:derivingUnbox), it appears people are passing in arbitrary strings as the constructor suffix.

Previous GHC/TH actually accepted constructor names with _spaces_ (yes, _spaces_) in them, but GHC 7.10 won't stand for that sort of shit. (And neither should we.)

**Comment by liyang** [comment]
@pacak should be watching this.

**Comment by pacak** [comment]
<img src="http://travelblawg.boardingarea.com/wp-content/uploads/2014/11/ceiling-cat.jpg">

**Comment by pacak** [comment]
But now it won't allow to use _ as part of the suffix!

**Comment by liyang** [comment]
Oh shi― Yes, I didn't read [§2.4 Identifiers and Operators](https://www.haskell.org/onlinereport/haskell2010/haskellch2.html#x7-180002.4) closely enough.
